# -*- coding: utf-8 -*-
"""PyQt_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n2H3_sV6cYydUIz45ZQxCOae5i7SJ472
"""

import sys
from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QPushButton, QListWidget, QVBoxLayout, QMessageBox

class BusStopApp(QWidget):
    def __init__(self):
        super().__init__()
        self.init_ui()

    def init_ui(self):
        self.label = QLabel('버스 번호를 선택하세요:', self)
        self.bus_list = QListWidget(self)
        self.info_button = QPushButton('정보 보기', self)

        buses = ['100', '200', '300', '400', '500']
        self.bus_list.addItems(buses)

        self.info_button.clicked.connect(self.show_bus_info)

        self.setWindowTitle('버스 정류장 프로그램')
        self.show()

    def show_bus_info(self):
        selected_bus = self.bus_list.currentItem()
        if selected_bus:
            bus_number = selected_bus.text()
            info = self.get_bus_info(bus_number)
            QMessageBox.information(self, f'버스 {bus_number} 정보', info)
        else:
            QMessageBox.warning(self, '경고', '버스를 선택하세요!')

    def get_bus_info(self, bus_number):
        bus_info = {
            '100': '도착까지 5분\n노선: 역삼 - 강남 - 신사',
            '200': '도착까지 2분\n노선: 잠실 - 송파 - 강동',
        }
        return bus_info.get(bus_number, '정보 없음')

if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = BusStopApp()
    sys.exit(app.exec_())