# -*- coding: utf-8 -*-
"""Tkinter_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n2H3_sV6cYydUIz45ZQxCOae5i7SJ472
"""

import tkinter as tk
from tkinter import messagebox

def order():
    selected_drinks = []
    for drink, var in drink_vars.items():
        if var.get():
            selected_drinks.append(drink)

    if selected_drinks:
        order_summary = "\n".join(selected_drinks)
        messagebox.showinfo("주문 완료", f"주문하신 음료:\n{order_summary}")
    else:
        messagebox.showwarning("선택 없음", "음료를 선택해주세요!")

root = tk.Tk()
root.title("음료 주문 프로그램")
root.geometry("400x600")

label = tk.Label(root, text="주문할 음료를 선택하세요", font=("Arial", 16))
label.pack(pady=10)

menu = {
    "커피": ["아메리카노", "카페라떼", "카푸치노", "카라멜 마끼아또", "바닐라 라떼"],
    "차": ["녹차", "홍차", "페퍼민트티", "캐모마일"],
    "주스": ["오렌지 주스", "망고 주스", "사과 주스", "자몽 주스"],
    "스무디": ["딸기 스무디", "블루베리 스무디", "망고 스무디"]
}

drink_vars = {}

for category, drinks in menu.items():
    cat_label = tk.Label(root, text=category, font=("Arial", 14, "bold"))
    cat_label.pack(pady=5)

    for drink in drinks:
        var = tk.BooleanVar()
        chk = tk.Checkbutton(root, text=drink, variable=var, font=("Arial", 12))
        chk.pack(anchor='w', padx=30)
        drink_vars[drink] = var

order_btn = tk.Button(root, text="주문하기", command=order, font=("Arial", 14), bg="lightblue")
order_btn.pack(pady=20)

root.mainloop()
